# frozen_string_literal: true
require "json"
require "digest"

module Magentic
  module Runtime
    # Stage 3 -- PACKAGE. Turns an APPROVED result into a deployable Magentic Component:
    #   component.yaml (image ref + release-packet digests) + a component Dockerfile that
    #   LABELs the image with the release-packet digest. Content-addresses the component
    #   and fills the packet's component_digest via ReleasePacket.reseal (re-signed).
    class Package
      def initialize(out_dir, image: nil, port: 3000)
        @out = out_dir.to_s
        @port = port
        @image = image
      end

      def call
        pkt_path = File.join(@out, "release-packet.json")
        return refuse(:not_approved, "approve first: release-packet.json missing") unless File.file?(pkt_path)
        pkt = JSON.parse(File.read(pkt_path))
        body = pkt["body"]
        image = @image || "#{body['flow_id']}:latest"

        component = {
          "apiVersion" => "magentic/component-v1",
          "name" => body["flow_id"],
          "image" => image,
          "port" => @port,
          "contract_set_digest" => body["contract_set_digest"],
          "public_projection_digest" => body["public_projection_digest"],
          "provenance_root" => body["provenance_root"],
          "edge_grant" => body["edge_grant"]
        }
        component_digest = "sha256:" + Digest::SHA256.hexdigest(RR::Grammar::CanonicalJson.dump(component))

        resealed = RR::Grammar::ReleasePacket.reseal(pkt, component_digest: component_digest)
        return refuse(:reseal_failed, resealed[:because]) unless resealed[:ok]
        component["release_packet_digest"] = resealed[:packet_sha256]

        write("component.yaml", to_yaml(component))
        write("release-packet.json", JSON.pretty_generate(resealed[:packet]))
        write("Dockerfile.component", dockerfile(image, component_digest, resealed[:packet_sha256]))

        { ok: true, out_dir: @out, image: image, component_digest: component_digest,
          release_packet_digest: resealed[:packet_sha256] }
      rescue StandardError => e
        refuse(:package_error, "#{e.class}: #{e.message}")
      end

      private

      def dockerfile(image, comp_digest, packet_digest)
        <<~DOCK
          # Generated by `magentic package` -- the Magentic Component image.
          # LABELs bind the running workload to its governed release evidence.
          FROM ruby:3.3-slim
          LABEL magentic.component.digest="#{comp_digest}"
          LABEL magentic.release_packet.digest="#{packet_digest}"
          WORKDIR /app
          COPY . /app
          EXPOSE #{@port}
          # CMD is the component's app entrypoint (todo-host, etc.)
        DOCK
      end

      def to_yaml(h)
        # tiny deterministic YAML (avoid ordering surprises); values are simple scalars/hashes
        lines = []
        h.each do |k, v|
          if v.is_a?(Hash)
            lines << "#{k}:"
            v.each { |kk, vv| lines << "  #{kk}: #{scalar(vv)}" }
          else
            lines << "#{k}: #{scalar(v)}"
          end
        end
        lines.join("\n") + "\n"
      end

      def scalar(v)
        return v.map { |x| x.to_s }.inspect if v.is_a?(Array)
        s = v.to_s
        s.match?(/\A[\w.:\/-]+\z/) ? s : s.inspect
      end

      def write(name, body) = File.write(File.join(@out, name), body)
      def refuse(reason, because) = { ok: false, reason: reason, because: because }
    end
  end
end
